<?php 
/**
 * ZF2rapid skeleton application
 * 
 * @package    Application
 * @link      https://github.com/ZFrapid/zf2rapid-skeleton
 * @copyright Copyright (c) 2014 Ralf Eggert
 * @license   http://opensource.org/licenses/MIT The MIT License (MIT)
 */

/**
 * Index view script
 * 
 * @package    Application
 */

$this->headTitle('Server Fehler');
$this->h1('Server Fehler');
?>
<div class="hero-unit">
<h1>Es ist ein Server Fehler aufgetreten!</h1>
</div>
<p class="pull-center"><a href="/" class="btn">Zur Startseite</a></p>
<hr />
<div class="alert alert-error">
<h2>Es ist ein interner Server Fehler aufgetreten.</h2>
<p>Bitte später noch einmal versuchen.</p>
</div>

<?php if (isset($this->display_exceptions) && $this->display_exceptions): ?>
    <?php if(isset($this->exception) && $this->exception instanceof Exception): ?>
        <?php $e = $this->exception->getPrevious(); ?>
        <div class="well">
        <h3>Weitere Informationen</h3>
        <table class="table">
        <tr>
        <th>Exception</th>
        <td><?php echo get_class($this->exception); ?></td>
        </tr>
        <tr>
        <th>Datei</th>
        <td><pre class="brush: php"><?php echo $this->exception->getFile() ?>:<?php echo $this->exception->getLine() ?>
&nbsp;
</pre></td>
        </tr>
        <tr>
        <th>Meldung</th>
        <td><pre class="brush: php"><?php echo $this->exception->getMessage() ?>
&nbsp;
</pre></td>
        </tr>
        <tr>
        <th>Stack&nbsp;Trace</th>
        <td><pre class="brush: php"><?php echo $this->exception->getTraceAsString() ?>
&nbsp;
</pre></td>
        </tr>
        </table>
        </div>
        <?php if ($e) : ?>
            <hr/>
            <div class="well">
            <h3>Vorherige Exceptions</h3>
            <?php while($e) : ?>
                <table class="table">
                <tr>
                <th>Exception</th>
                <td><?php echo get_class($e); ?></td>
                </tr>
                <tr>
                <th>Datei</th>
                <td><pre class="brush: php"><?php echo $e->getFile() ?>:<?php echo $e->getLine() ?>
&nbsp;
</pre></td>
                </tr>
                <tr>
                <th>Meldung</th>
                <td><pre class="brush: php"><?php echo $e->getMessage() ?>
&nbsp;
</pre></td>
                </tr>
                <tr>
                <th>Stack&nbsp;Trace</th>
                <td><pre class="brush: php"><?php echo $e->getTraceAsString() ?>
&nbsp;
</pre></td>
                </tr>
                </table>
                <hr/>
                <?php $e = $e->getPrevious(); ?>
            <?php endwhile; ?>
            </div>
        <?php endif; ?>
    <?php else: ?>
        <h3>Keine Exception vorhanden</h3>
    <?php endif ?>
<?php endif ?>
