<?php
/**
 * ZF2rapid skeleton application
 *
 * @package    Application
 * @link       https://github.com/ZFrapid/zf2rapid-skeleton
 * @copyright  Copyright (c) 2014 Ralf Eggert
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 *
 * @todo       List features and use FontAwesome Icons
 */

/**
 * Index view script
 *
 * @package    Application
 */

$this->h1('application_h1_index_index');

?>
<div class="row">
    <div class="col-md-3 col-sm-6">
        <h2>
            <i class="fa fa-question"></i>
            <?php echo $this->translate('application_h2_index_whatever'); ?>
        </h2>
        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>
    </div>
    <div class="col-md-3 col-sm-6">
        <h2>
            <i class="fa fa-wrench"></i>
            <?php echo $this->translate('application_h2_index_features'); ?>
        </h2>
        <p>Some basic Zend Framework 2 features are activated to help you to get started with your ZF2 application.</p>
        <ul class="fa-ul">
            <li>
                <i class="fa-li fa fa-thumbs-up"></i>
                Translations (English/German)
            </li>
            <li>
                <i class="fa-li fa fa-thumbs-up"></i>
                Multi-level layout
            </li>
            <li>
                <i class="fa-li fa fa-thumbs-up"></i>
                Session configuration
            </li>
            <li>
                <i class="fa-li fa fa-thumbs-up"></i>
                Navigation configuration
            </li>
        </ul>
    </div>
    <div class="col-md-3 col-sm-6">
        <h2>
            <i class="fa fa-cubes"></i>
            <?php echo $this->translate('application_h2_index_modules'); ?>
        </h2>
        <p>Some useful Zend Framework 2 modules are installed and activated for your convenience.</p>
        <ul class="fa-ul">
            <li>
                <i class="fa-li fa fa-thumbs-up"></i>
                Zend Developer Tools
            </li>
            <li>
                <i class="fa-li fa fa-thumbs-up"></i>
                BjyProfiler
            </li>
            <li>
                <i class="fa-li fa fa-thumbs-up"></i>
                SanSessionToolbar
            </li>
        </ul>
    </div>
    <div class="col-md-3 col-sm-6">
        <h2>
            <i class="fa fa-desktop"></i>
            <?php echo $this->translate('application_h2_index_frontend'); ?>
        </h2>
        <p>Frontend libraries are installed by Composer and symlinked to the public folder of the application.</p>
        <ul class="fa-ul">
            <li>
                <i class="fa-li fa fa-thumbs-up"></i>
                Bootstrap 3.x
            </li>
            <li>
                <i class="fa-li fa fa-thumbs-up"></i>
                Font Awesome 4.x
            </li>
            <li>
                <i class="fa-li fa fa-thumbs-up"></i>
                jQuery 1.11.x
            </li>
        </ul>
    </div>
</div>
